import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import pg from 'pg'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import fs from 'fs'; import path from 'path'; import {v2 as cloudinary} from 'cloudinary';
const app=express(), {Pool}=pg; const PORT=process.env.PORT||10000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
const uploadDir=path.resolve('uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>cb(null,file.mimetype.startsWith('image/'))});
app.use(cors()); app.use(express.json({limit:'2mb'})); app.use('/uploads',express.static(uploadDir)); app.use(express.static('public'));
if(process.env.CLOUDINARY_URL) cloudinary.config({secure:true});
const q=(text,params=[])=>pool.query(text,params);
const slugify=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function admin(req,res,next){const token=(req.headers.authorization||'').replace('Bearer ','');try{req.user=jwt.verify(token,process.env.JWT_SECRET||'dev-secret');next()}catch{return res.status(401).json({error:'No autorizado'})}}

app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/categories',async(req,res)=>{const r=await q('SELECT * FROM categories ORDER BY sort_order,name');res.json(r.rows)});
app.get('/api/products',async(req,res)=>{const {category,featured,search,admin:all}=req.query;let sql=`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(json_agg(json_build_object('id',i.id,'url',i.url,'position',i.position)) ORDER BY i.position) FILTER (WHERE i.id IS NOT NULL),'[]') images FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN product_images i ON i.product_id=p.id WHERE 1=1`;let vals=[];if(all!=='1')sql+=' AND p.active=true';if(category){vals.push(category);sql+=` AND c.slug=$${vals.length}`}if(featured==='1')sql+=' AND p.featured=true';if(search){vals.push(`%${search}%`);sql+=` AND (p.name ILIKE $${vals.length} OR p.sku ILIKE $${vals.length})`}sql+=' GROUP BY p.id,c.name,c.slug ORDER BY p.featured DESC,p.created_at DESC';const r=await q(sql,vals);res.json(r.rows)});
app.get('/api/products/:slug',async(req,res)=>{const r=await q(`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(json_agg(json_build_object('id',i.id,'url',i.url,'position',i.position)) ORDER BY i.position) FILTER (WHERE i.id IS NOT NULL),'[]') images FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN product_images i ON i.product_id=p.id WHERE p.slug=$1 GROUP BY p.id,c.name,c.slug`,[req.params.slug]);if(!r.rowCount)return res.status(404).json({error:'Producto no encontrado'});res.json(r.rows[0])});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;const r=await q('SELECT * FROM users WHERE email=$1',[email]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash))return res.status(401).json({error:'Credenciales incorrectas'});const u=r.rows[0];const token=jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET||'dev-secret',{expiresIn:'12h'});res.json({token,user:{name:u.name,email:u.email}})});
app.get('/api/admin/stats',admin,async(req,res)=>{const [p,stock,value,low,orders]=await Promise.all([q('SELECT count(*)::int total FROM products WHERE active=true'),q('SELECT COALESCE(sum(stock),0)::int total FROM products WHERE active=true'),q('SELECT COALESCE(sum(stock*price),0)::numeric value FROM products WHERE active=true'),q('SELECT id,name,stock FROM products WHERE active=true AND stock<=3 ORDER BY stock ASC LIMIT 8'),q(`SELECT count(*)::int total,COALESCE(sum(total),0)::numeric revenue FROM orders WHERE created_at>=date_trunc('month',NOW())`)]);res.json({products:p.rows[0].total,units:stock.rows[0].total,inventoryValue:value.rows[0].value,lowStock:low.rows,monthOrders:orders.rows[0].total,monthRevenue:orders.rows[0].revenue})});
app.post('/api/admin/products',admin,async(req,res)=>{const b=req.body;const slug=slugify(b.name)+'-'+Date.now().toString().slice(-5);const r=await q(`INSERT INTO products(sku,name,slug,category_id,brand,description,material,price,compare_at_price,stock,sizes,featured,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true) RETURNING *`,[b.sku||null,b.name,slug,b.category_id||null,b.brand||'Fossil',b.description||'',b.material||'',b.price||0,b.compare_at_price||null,b.stock||0,b.sizes||[],!!b.featured]);if(Number(b.stock)>0)await q("INSERT INTO inventory_movements(product_id,type,quantity,note) VALUES($1,'IN',$2,'Stock inicial')",[r.rows[0].id,b.stock]);res.status(201).json(r.rows[0])});
app.patch('/api/admin/products/:id',admin,async(req,res)=>{const b=req.body;const r=await q(`UPDATE products SET name=COALESCE($2,name),category_id=COALESCE($3,category_id),brand=COALESCE($4,brand),description=COALESCE($5,description),material=COALESCE($6,material),price=COALESCE($7,price),compare_at_price=$8,sizes=COALESCE($9,sizes),featured=COALESCE($10,featured),active=COALESCE($11,active),updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,b.name,b.category_id,b.brand,b.description,b.material,b.price,b.compare_at_price,b.sizes,b.featured,b.active]);res.json(r.rows[0])});
app.post('/api/admin/products/:id/inventory',admin,async(req,res)=>{const {type,quantity,note}=req.body;const qty=Number(quantity);if(!Number.isInteger(qty)||qty===0)return res.status(400).json({error:'Cantidad inválida'});const client=await pool.connect();try{await client.query('BEGIN');const cur=await client.query('SELECT stock FROM products WHERE id=$1 FOR UPDATE',[req.params.id]);if(!cur.rowCount)throw Error('Producto no encontrado');let delta=['OUT','SALE'].includes(type)?-Math.abs(qty):Math.abs(qty);if(type==='ADJUSTMENT')delta=qty;if(cur.rows[0].stock+delta<0)throw Error('Stock insuficiente');await client.query('UPDATE products SET stock=stock+$2,updated_at=NOW() WHERE id=$1',[req.params.id,delta]);await client.query('INSERT INTO inventory_movements(product_id,type,quantity,note) VALUES($1,$2,$3,$4)',[req.params.id,type,delta,note||null]);await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/admin/inventory/:id',admin,async(req,res)=>{const r=await q('SELECT * FROM inventory_movements WHERE product_id=$1 ORDER BY created_at DESC LIMIT 100',[req.params.id]);res.json(r.rows)});
app.post('/api/admin/products/:id/images',admin,upload.array('images',8),async(req,res)=>{if(!req.files?.length)return res.status(400).json({error:'Selecciona al menos una imagen'});const urls=[];for(const f of req.files){let url,publicId=null;if(process.env.CLOUDINARY_URL){const up=await cloudinary.uploader.upload(f.path,{folder:'fossil-products'});fs.unlinkSync(f.path);url=up.secure_url;publicId=up.public_id}else{const ext=path.extname(f.originalname)||'.jpg';const name=`${Date.now()}-${Math.random().toString(36).slice(2)}${ext}`;fs.renameSync(f.path,path.join(uploadDir,name));url=`/uploads/${name}`}const pos=urls.length;const r=await q('INSERT INTO product_images(product_id,url,public_id,position) VALUES($1,$2,$3,$4) RETURNING *',[req.params.id,url,publicId,pos]);urls.push(r.rows[0])}res.status(201).json(urls)});
app.post('/api/orders',async(req,res)=>{const {items,customer={}}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Carrito vacío'});const client=await pool.connect();try{await client.query('BEGIN');let total=0,prepared=[];for(const x of items){const r=await client.query('SELECT id,name,price,stock FROM products WHERE id=$1 AND active=true FOR UPDATE',[x.product_id]);if(!r.rowCount)throw Error('Producto no disponible');const p=r.rows[0],qty=Math.max(1,Number(x.quantity||1));if(p.stock<qty)throw Error(`${p.name}: stock insuficiente`);total+=Number(p.price)*qty;prepared.push({p,qty,size:x.size||null})}const o=await client.query('INSERT INTO orders(customer_name,customer_phone,customer_email,total) VALUES($1,$2,$3,$4) RETURNING *',[customer.name||null,customer.phone||null,customer.email||null,total]);for(const x of prepared){await client.query('INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,size) VALUES($1,$2,$3,$4,$5,$6)',[o.rows[0].id,x.p.id,x.p.name,x.qty,x.p.price,x.size]);await client.query('UPDATE products SET stock=stock-$2 WHERE id=$1',[x.p.id,x.qty]);await client.query("INSERT INTO inventory_movements(product_id,type,quantity,note) VALUES($1,'SALE',$2,$3)",[x.p.id,-x.qty,`Pedido web #${o.rows[0].id}`])}await client.query('COMMIT');res.status(201).json({order:o.rows[0]})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('*',(req,res)=>res.sendFile(path.resolve('public/index.html')));
app.listen(PORT,()=>console.log(`Fossil en http://localhost:${PORT}`));
